<?php
declare(strict_types=1);

namespace PCF\Addendum\Tests\Entity\User;

use PCF\Addendum\Entity\User\Admin;
use PHPUnit\Framework\TestCase;
use DateTimeImmutable;
use InvalidArgumentException;
use LogicException;

final class AdminTest extends TestCase
{
    public function testFromDatabaseRowCreatesAdminCorrectly(): void
    {
        $row = [
            'id' => 1,
            'uuid' => 'admin-uuid-123',
            'user_uuid' => 'user-uuid-456',
            'granted_at' => '2024-01-15 10:00:00',
            'granted_by_user_uuid' => 'granter-uuid-789',
            'granted_reason' => 'System administrator',
            'revoked_at' => null,
            'revoked_by_user_uuid' => null,
            'revoked_reason' => null,
        ];

        $admin = Admin::fromDatabaseRow($row);

        $this->assertSame(1, $admin->id);
        $this->assertSame('admin-uuid-123', $admin->uuid);
        $this->assertSame('user-uuid-456', $admin->userUuid);
        $this->assertSame('granter-uuid-789', $admin->grantedByUserUuid);
        $this->assertSame('System administrator', $admin->grantedReason);
        $this->assertNull($admin->revokedAt);
        $this->assertNull($admin->revokedByUserUuid);
        $this->assertNull($admin->revokedReason);
    }

    public function testFromDatabaseRowWithRevokedAdmin(): void
    {
        $row = [
            'id' => 1,
            'uuid' => 'admin-uuid-123',
            'user_uuid' => 'user-uuid-456',
            'granted_at' => '2024-01-15 10:00:00',
            'granted_by_user_uuid' => null,
            'granted_reason' => null,
            'revoked_at' => '2024-02-15 10:00:00',
            'revoked_by_user_uuid' => 'revoker-uuid-111',
            'revoked_reason' => 'No longer needed',
        ];

        $admin = Admin::fromDatabaseRow($row);

        $this->assertNotNull($admin->revokedAt);
        $this->assertSame('revoker-uuid-111', $admin->revokedByUserUuid);
        $this->assertSame('No longer needed', $admin->revokedReason);
    }

    public function testCreateNewAdmin(): void
    {
        $admin = Admin::create(
            userUuid: 'user-uuid-123',
            grantedByUserUuid: 'granter-uuid-456',
            grantedReason: 'Promoted to admin'
        );

        $this->assertSame(0, $admin->id); // Assigned by database
        $this->assertSame('', $admin->uuid); // Generated by database
        $this->assertSame('user-uuid-123', $admin->userUuid);
        $this->assertSame('granter-uuid-456', $admin->grantedByUserUuid);
        $this->assertSame('Promoted to admin', $admin->grantedReason);
        $this->assertNull($admin->revokedAt);
    }

    public function testCreateNewAdminViaCli(): void
    {
        $admin = Admin::create(
            userUuid: 'user-uuid-123',
            grantedByUserUuid: null,
            grantedReason: 'CLI grant'
        );

        $this->assertNull($admin->grantedByUserUuid);
        $this->assertTrue($admin->isGrantedViaCli);
    }

    public function testIsActivePropertyHookForActiveAdmin(): void
    {
        $admin = Admin::create(userUuid: 'user-uuid-123');

        $this->assertTrue($admin->isActive);
    }

    public function testIsActivePropertyHookForRevokedAdmin(): void
    {
        $row = [
            'id' => 1,
            'uuid' => 'admin-uuid-123',
            'user_uuid' => 'user-uuid-456',
            'granted_at' => '2024-01-15 10:00:00',
            'revoked_at' => '2024-02-15 10:00:00',
        ];

        $admin = Admin::fromDatabaseRow($row);

        $this->assertFalse($admin->isActive);
    }

    public function testIsGrantedViaCliPropertyHook(): void
    {
        $cliAdmin = Admin::create(userUuid: 'user-uuid', grantedByUserUuid: null);
        $userAdmin = Admin::create(userUuid: 'user-uuid', grantedByUserUuid: 'granter-uuid');

        $this->assertTrue($cliAdmin->isGrantedViaCli);
        $this->assertFalse($userAdmin->isGrantedViaCli);
    }

    public function testIsRevokedViaCliPropertyHook(): void
    {
        $row = [
            'id' => 1,
            'uuid' => 'admin-uuid-123',
            'user_uuid' => 'user-uuid-456',
            'granted_at' => '2024-01-15 10:00:00',
            'revoked_at' => '2024-02-15 10:00:00',
            'revoked_by_user_uuid' => null, // CLI revocation
        ];

        $admin = Admin::fromDatabaseRow($row);

        $this->assertTrue($admin->isRevokedViaCli);
    }

    public function testIsRevokedViaCliReturnsFalseForUserRevocation(): void
    {
        $row = [
            'id' => 1,
            'uuid' => 'admin-uuid-123',
            'user_uuid' => 'user-uuid-456',
            'granted_at' => '2024-01-15 10:00:00',
            'revoked_at' => '2024-02-15 10:00:00',
            'revoked_by_user_uuid' => 'revoker-uuid',
        ];

        $admin = Admin::fromDatabaseRow($row);

        $this->assertFalse($admin->isRevokedViaCli);
    }

    public function testIsRevokedViaCliReturnsFalseForActiveAdmin(): void
    {
        $admin = Admin::create(userUuid: 'user-uuid');

        $this->assertFalse($admin->isRevokedViaCli);
    }

    public function testDaysSinceGrantedPropertyHook(): void
    {
        $pastDate = (new DateTimeImmutable())->modify('-10 days');

        $row = [
            'id' => 1,
            'uuid' => 'admin-uuid-123',
            'user_uuid' => 'user-uuid-456',
            'granted_at' => $pastDate->format('Y-m-d H:i:s'),
        ];

        $admin = Admin::fromDatabaseRow($row);

        $this->assertSame(10, $admin->daysSinceGranted);
    }

    public function testDaysSinceGrantedForNewAdmin(): void
    {
        $admin = Admin::create(userUuid: 'user-uuid');

        $this->assertSame(0, $admin->daysSinceGranted);
    }

    public function testDaysSinceRevokedPropertyHookForRevokedAdmin(): void
    {
        $grantDate = (new DateTimeImmutable())->modify('-30 days');
        $revokeDate = (new DateTimeImmutable())->modify('-5 days');

        $row = [
            'id' => 1,
            'uuid' => 'admin-uuid-123',
            'user_uuid' => 'user-uuid-456',
            'granted_at' => $grantDate->format('Y-m-d H:i:s'),
            'revoked_at' => $revokeDate->format('Y-m-d H:i:s'),
        ];

        $admin = Admin::fromDatabaseRow($row);

        $this->assertSame(5, $admin->daysSinceRevoked);
    }

    public function testDaysSinceRevokedReturnsNullForActiveAdmin(): void
    {
        $admin = Admin::create(userUuid: 'user-uuid');

        $this->assertNull($admin->daysSinceRevoked);
    }

    public function testWithRevocationCreatesRevokedAdmin(): void
    {
        $admin = Admin::create(userUuid: 'user-uuid-123');
        $revokedAt = new DateTimeImmutable();

        $revokedAdmin = $admin->withRevocation(
            revokedAt: $revokedAt,
            revokedByUserUuid: 'revoker-uuid',
            reason: 'Security incident'
        );

        $this->assertTrue($admin->isActive); // Original unchanged
        $this->assertFalse($revokedAdmin->isActive);
        $this->assertSame($revokedAt, $revokedAdmin->revokedAt);
        $this->assertSame('revoker-uuid', $revokedAdmin->revokedByUserUuid);
        $this->assertSame('Security incident', $revokedAdmin->revokedReason);
    }

    public function testWithRevocationThrowsExceptionIfAlreadyRevoked(): void
    {
        $row = [
            'id' => 1,
            'uuid' => 'admin-uuid-123',
            'user_uuid' => 'user-uuid-456',
            'granted_at' => '2024-01-15 10:00:00',
            'revoked_at' => '2024-02-15 10:00:00',
        ];

        $admin = Admin::fromDatabaseRow($row);

        $this->expectException(LogicException::class);
        $this->expectExceptionMessage('Admin privileges already revoked');

        $admin->withRevocation(new DateTimeImmutable());
    }

    public function testValidationRejectsEmptyUserUuid(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('User UUID cannot be empty');

        Admin::create(userUuid: '');
    }

    public function testValidationRejectsRevokedBeforeGranted(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('Revoked date cannot be before granted date');

        $row = [
            'id' => 1,
            'uuid' => 'admin-uuid-123',
            'user_uuid' => 'user-uuid-456',
            'granted_at' => '2024-02-15 10:00:00',
            'revoked_at' => '2024-01-15 10:00:00', // Before granted
        ];

        Admin::fromDatabaseRow($row);
    }

    public function testIsGrantedByMethod(): void
    {
        $admin = Admin::create(
            userUuid: 'user-uuid',
            grantedByUserUuid: 'granter-uuid-123'
        );

        $this->assertTrue($admin->isGrantedBy('granter-uuid-123'));
        $this->assertFalse($admin->isGrantedBy('other-uuid'));
    }

    public function testIsRevokedByMethod(): void
    {
        $admin = Admin::create(userUuid: 'user-uuid');
        $revokedAdmin = $admin->withRevocation(
            new DateTimeImmutable(),
            revokedByUserUuid: 'revoker-uuid-123'
        );

        $this->assertTrue($revokedAdmin->isRevokedBy('revoker-uuid-123'));
        $this->assertFalse($revokedAdmin->isRevokedBy('other-uuid'));
    }

    public function testGetStatusMethod(): void
    {
        $activeAdmin = Admin::create(userUuid: 'user-uuid');
        $revokedAdmin = $activeAdmin->withRevocation(new DateTimeImmutable());

        $this->assertSame('ACTIVE', $activeAdmin->getStatus());
        $this->assertSame('REVOKED', $revokedAdmin->getStatus());
    }

    public function testGetGrantSourceMethod(): void
    {
        $cliAdmin = Admin::create(userUuid: 'user-uuid', grantedByUserUuid: null);
        $userAdmin = Admin::create(userUuid: 'user-uuid', grantedByUserUuid: 'granter-uuid');

        $this->assertSame('CLI', $cliAdmin->getGrantSource());
        $this->assertSame('User', $userAdmin->getGrantSource());
    }

    public function testGetRevocationSourceMethod(): void
    {
        $activeAdmin = Admin::create(userUuid: 'user-uuid');
        $cliRevokedAdmin = $activeAdmin->withRevocation(new DateTimeImmutable(), null);
        $userRevokedAdmin = $activeAdmin->withRevocation(new DateTimeImmutable(), 'revoker-uuid');

        $this->assertNull($activeAdmin->getRevocationSource());
        $this->assertSame('CLI', $cliRevokedAdmin->getRevocationSource());
        $this->assertSame('User', $userRevokedAdmin->getRevocationSource());
    }
}
