<?php
declare(strict_types=1);

namespace PCF\Addendum\Entity\User;

use DateTimeImmutable;

/**
 * Admin entity
 *
 * Represents admin privileges for a user. When a user has an active admin record:
 * - Their tokens use the framework admin token type
 * - They bypass all ownership checks
 * - They have full access to all resources
 *
 * Admin privileges can be:
 * - Granted via CLI command or by another admin
 * - Revoked with reason and audit trail
 * - Tracked with full audit history
 */
final class Admin
{
    /**
     * Computed property: Days since granted
     */
    public int $daysSinceGranted {
        get {
            $now = new DateTimeImmutable();
            $diff = $now->diff($this->grantedAt);
            return (int) $diff->days;
        }
    }

    /**
     * Computed property: Days since revoked (null if active)
     */
    public ?int $daysSinceRevoked {
        get {
            if ($this->revokedAt === null) {
                return null;
            }

            $now = new DateTimeImmutable();
            $diff = $now->diff($this->revokedAt);
            return (int) $diff->days;
        }
    }

    private function __construct(
        public int $id,
        public string $uuid,
        public string $userUuid,
        public DateTimeImmutable $grantedAt,
        public ?string $grantedByUserUuid = null,
        public ?string $grantedReason = null,
        public ?DateTimeImmutable $revokedAt = null,
        public ?string $revokedByUserUuid = null,
        public ?string $revokedReason = null
    ) {
        $this->validate();
    }

    /**
     * Create Admin from database row
     */
    public static function fromDatabaseRow(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            uuid: $row['uuid'],
            userUuid: $row['user_uuid'],
            grantedAt: new DateTimeImmutable($row['granted_at']),
            grantedByUserUuid: $row['granted_by_user_uuid'] ?? null,
            grantedReason: $row['granted_reason'] ?? null,
            revokedAt: isset($row['revoked_at']) ? new DateTimeImmutable($row['revoked_at']) : null,
            revokedByUserUuid: $row['revoked_by_user_uuid'] ?? null,
            revokedReason: $row['revoked_reason'] ?? null
        );
    }

    /**
     * Create new Admin for database insertion
     */
    public static function create(
        string $userUuid,
        ?string $grantedByUserUuid = null,
        ?string $grantedReason = null
    ): self {
        return new self(
            id: 0, // Will be assigned by database
            uuid: '', // Will be generated by database
            userUuid: $userUuid,
            grantedAt: new DateTimeImmutable(),
            grantedByUserUuid: $grantedByUserUuid,
            grantedReason: $grantedReason
        );
    }

    /**
     * Create new instance with revocation details
     */
    public function withRevocation(
        DateTimeImmutable $revokedAt,
        ?string $revokedByUserUuid = null,
        ?string $reason = null
    ): self {
        if ($this->revokedAt !== null) {
            throw new \LogicException('Admin privileges already revoked');
        }

        return new self(
            id: $this->id,
            uuid: $this->uuid,
            userUuid: $this->userUuid,
            grantedAt: $this->grantedAt,
            grantedByUserUuid: $this->grantedByUserUuid,
            grantedReason: $this->grantedReason,
            revokedAt: $revokedAt,
            revokedByUserUuid: $revokedByUserUuid,
            revokedReason: $reason
        );
    }

    /**
     * Validate admin data
     */
    private function validate(): void
    {
        if (empty($this->userUuid)) {
            throw new \InvalidArgumentException('User UUID cannot be empty');
        }

        if ($this->revokedAt !== null && $this->revokedAt < $this->grantedAt) {
            throw new \InvalidArgumentException('Revoked date cannot be before granted date');
        }
    }

    /**
     * Check if admin was granted by specific user
     */
    public function isGrantedBy(string $userUuid): bool
    {
        return $this->grantedByUserUuid === $userUuid;
    }

    /**
     * Check if admin was revoked by specific user
     */
    public function isRevokedBy(string $userUuid): bool
    {
        return $this->revokedByUserUuid === $userUuid;
    }

    public function isActive(): bool
    {
        return $this->revokedAt === null;
    }

    public function isGrantedViaCli(): bool
    {
        return $this->grantedByUserUuid === null;
    }

    public function isRevokedViaCli(): bool
    {
        return $this->revokedByUserUuid === null && $this->revokedAt !== null;
    }

    /**
     * Get status string
     */
    public function getStatus(): string
    {
        return $this->isActive() ? 'ACTIVE' : 'REVOKED';
    }

    /**
     * Get grant source (CLI or user email would be added by repository)
     */
    public function getGrantSource(): string
    {
        return $this->isGrantedViaCli() ? 'CLI' : 'User';
    }

    /**
     * Get revocation source
     */
    public function getRevocationSource(): ?string
    {
        if ($this->revokedAt === null) {
            return null;
        }

        return $this->isRevokedViaCli() ? 'CLI' : 'User';
    }
}
