<?php
declare(strict_types=1);

namespace PCF\Addendum\Entity\User;

use DateTimeImmutable;

/**
 * Application Token entity
 *
 * Represents a long-lived authentication token for external applications/services.
 * These tokens:
 * - Never expire (unless revoked)
 * - Have TOKEN_TYPE = APPLICATION
 * - Grant elevated privileges
 * - Track usage and ownership
 *
 * Security considerations:
 * - Token hash is stored (not plain token)
 * - JTI enables revocation checking
 * - Owner information for accountability
 * - Usage tracking for auditing
 */
final readonly class ApplicationToken
{
    private function __construct(
        public int $id,
        public string $uuid,
        public string $tokenHash,
        public string $applicationName,
        public string $ownerName,
        public string $ownerEmail,
        public string $jti,
        public DateTimeImmutable $createdAt,
        public ?DateTimeImmutable $lastUsedAt = null,
        public ?DateTimeImmutable $revokedAt = null,
        public ?string $revokedReason = null
    ) {
        $this->validate();
    }

    /**
     * Create new ApplicationToken from database row
     */
    public static function fromDatabaseRow(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            uuid: $row['uuid'],
            tokenHash: $row['token_hash'],
            applicationName: $row['application_name'],
            ownerName: $row['owner_name'],
            ownerEmail: $row['owner_email'],
            jti: $row['jti'],
            createdAt: new DateTimeImmutable($row['created_at']),
            lastUsedAt: isset($row['last_used_at']) ? new DateTimeImmutable($row['last_used_at']) : null,
            revokedAt: isset($row['revoked_at']) ? new DateTimeImmutable($row['revoked_at']) : null,
            revokedReason: $row['revoked_reason'] ?? null
        );
    }

    /**
     * Create new ApplicationToken for database insertion
     */
    public static function create(
        string $tokenHash,
        string $applicationName,
        string $ownerName,
        string $ownerEmail,
        string $jti
    ): self {
        return new self(
            id: 0, // Will be assigned by database
            uuid: '', // Will be generated by database
            tokenHash: $tokenHash,
            applicationName: $applicationName,
            ownerName: $ownerName,
            ownerEmail: $ownerEmail,
            jti: $jti,
            createdAt: new DateTimeImmutable()
        );
    }

    /**
     * Create new instance with updated last used timestamp
     */
    public function withLastUsedAt(DateTimeImmutable $lastUsedAt): self
    {
        return new self(
            id: $this->id,
            uuid: $this->uuid,
            tokenHash: $this->tokenHash,
            applicationName: $this->applicationName,
            ownerName: $this->ownerName,
            ownerEmail: $this->ownerEmail,
            jti: $this->jti,
            createdAt: $this->createdAt,
            lastUsedAt: $lastUsedAt,
            revokedAt: $this->revokedAt,
            revokedReason: $this->revokedReason
        );
    }

    /**
     * Create new instance with revocation details
     */
    public function withRevocation(DateTimeImmutable $revokedAt, ?string $reason = null): self
    {
        if ($this->revokedAt !== null) {
            throw new \LogicException('Token is already revoked');
        }

        return new self(
            id: $this->id,
            uuid: $this->uuid,
            tokenHash: $this->tokenHash,
            applicationName: $this->applicationName,
            ownerName: $this->ownerName,
            ownerEmail: $this->ownerEmail,
            jti: $this->jti,
            createdAt: $this->createdAt,
            lastUsedAt: $this->lastUsedAt,
            revokedAt: $revokedAt,
            revokedReason: $reason
        );
    }

    /**
     * Validate token data
     */
    private function validate(): void
    {
        if (strlen($this->applicationName) < 3) {
            throw new \InvalidArgumentException('Application name must be at least 3 characters');
        }

        if (strlen($this->ownerName) < 2) {
            throw new \InvalidArgumentException('Owner name must be at least 2 characters');
        }

        if (!filter_var($this->ownerEmail, FILTER_VALIDATE_EMAIL)) {
            throw new \InvalidArgumentException('Invalid owner email format');
        }

        if (empty($this->tokenHash)) {
            throw new \InvalidArgumentException('Token hash cannot be empty');
        }

        if (empty($this->jti)) {
            throw new \InvalidArgumentException('JTI cannot be empty');
        }
    }

    /**
     * Get days since creation
     */
    public function getDaysSinceCreation(): int
    {
        $now = new DateTimeImmutable();
        $diff = $now->diff($this->createdAt);
        return (int) $diff->days;
    }

    /**
     * Get days since last use (null if never used)
     */
    public function getDaysSinceLastUse(): ?int
    {
        if ($this->lastUsedAt === null) {
            return null;
        }

        $now = new DateTimeImmutable();
        $diff = $now->diff($this->lastUsedAt);
        return (int) $diff->days;
    }

    /**
     * Check if token is owned by specific email
     */
    public function isOwnedBy(string $email): bool
    {
        return strcasecmp($this->ownerEmail, $email) === 0;
    }

    /**
     * Check if token belongs to specific application
     */
    public function belongsToApplication(string $applicationName): bool
    {
        return strcasecmp($this->applicationName, $applicationName) === 0;
    }

    /**
     * Check if token is active (not revoked)
     */
    public function isActive(): bool
    {
        return $this->revokedAt === null;
    }

    /**
     * Check if token has been used
     */
    public function hasBeenUsed(): bool
    {
        return $this->lastUsedAt !== null;
    }

    /**
     * Check if token was used recently (within 7 days)
     */
    public function isRecentlyUsed(): bool
    {
        if ($this->lastUsedAt === null) {
            return false;
        }

        $sevenDaysAgo = new DateTimeImmutable('-7 days');
        return $this->lastUsedAt >= $sevenDaysAgo;
    }
}
