<?php

declare(strict_types=1);

namespace PCF\Addendum\Http\Routing;

use Nette\PhpGenerator\Closure;
use Nette\PhpGenerator\Literal;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\Printer;
use PCF\Addendum\Attribute\ResourcePolicy;
use PCF\Addendum\Http\Cache\ResourcePolicyCollection;
use PCF\Addendum\Http\RegisteredRoute;
use PCF\Addendum\Http\RouteCollection;
use PCF\Addendum\Http\RouteMiddleware;
use PCF\Addendum\Http\RouteMiddlewareCollection;

final readonly class CompiledRouteCollectionGenerator
{
    public function generate(RouteCollection $routes): string
    {
        $file = new PhpFile();
        $file->setStrictTypes();
        $file->addComment('This file is auto-generated by Addendum. Do not edit it manually.');

        $closure = new Closure();
        $closure->setReturnType(RouteCollection::class);
        $closure->addBody('$routes = new \\' . RouteCollection::class . '();');
        $closure->addBody('');

        foreach ($routes->getAllRoutes() as $method => $registeredRoutes) {
            foreach ($registeredRoutes as $route) {
                $closure->addBody('$routes->addRoute(?, ?);', [$method, new Literal($this->routeCode($route))]);
            }
        }

        $closure->addBody('');
        $closure->addBody('return $routes;');

        $printer = new Printer();
        $printer->declareOnOpenTag = false;

        return (string) $file . "\nreturn " . $printer->printClosure($closure) . ";\n";
    }

    private function routeCode(RegisteredRoute $route): string
    {
        return sprintf(
            'new \\%s(pattern: %s, actionClass: \\%s::class, middlewares: %s, resourcePolicies: %s, path: %s)',
            RegisteredRoute::class,
            $this->dump($route->pattern),
            ltrim($route->actionClass, '\\'),
            $this->middlewaresCode($route->middlewares),
            $this->resourcePoliciesCode($route->resourcePolicies),
            $this->dump($route->path)
        );
    }

    private function middlewaresCode(RouteMiddlewareCollection $middlewares): string
    {
        if ($middlewares->isEmpty()) {
            return 'new \\' . RouteMiddlewareCollection::class . '()';
        }

        $items = [];

        foreach ($middlewares as $middleware) {
            $options = $middleware->getOptions();
            $items[] = sprintf(
                'new \\%s(\\%s::class, %s)',
                RouteMiddleware::class,
                ltrim($middleware->getClass(), '\\'),
                new RouteMiddlewareOptionsCodeGenerator()->generate($options)
            );
        }

        return sprintf(
            "new \\%s([\n%s,\n])",
            RouteMiddlewareCollection::class,
            $this->indent(implode(",\n", $items))
        );
    }

    private function resourcePoliciesCode(ResourcePolicyCollection $policies): string
    {
        $items = [];

        foreach ($policies->all() as $policy) {
            $items[] = sprintf(
                'new \\%s(mode: \\%s::%s, maxAge: %d, resource: %s, idAttribute: %s, cacheErrors: %s)',
                ResourcePolicy::class,
                $policy->mode::class,
                $policy->mode->name,
                $policy->maxAge,
                $this->dump($policy->resource),
                $this->dump($policy->idAttribute),
                $policy->cacheErrors ? 'true' : 'false'
            );
        }

        return sprintf(
            "new \\%s([\n%s,\n])",
            ResourcePolicyCollection::class,
            $this->indent(implode(",\n", $items))
        );
    }

    private function dump(mixed $value): string
    {
        return new RouteMiddlewareOptionsCodeGenerator()->valueCode($value);
    }

    private function indent(string $code): string
    {
        return preg_replace('/^/m', '    ', $code) ?? $code;
    }
}
