<?php
declare(strict_types=1);

namespace PCF\Addendum\Application\Cache;

final readonly class CompiledHttpApplicationGenerator
{
    public function generate(): string
    {
        return <<<'PHP'
<?php
declare(strict_types=1);

// This file is auto-generated by Addendum. Do not edit it manually.

return static function (): \PCF\Addendum\Application\App {
    $routesFactory = require __DIR__ . '/routes.php';

    if (!is_callable($routesFactory)) {
        throw new \RuntimeException('Compiled routes file must return a callable');
    }

    $routes = $routesFactory();

    if (!$routes instanceof \PCF\Addendum\Http\RouteCollection) {
        throw new \RuntimeException('Compiled routes factory must return RouteCollection');
    }

    $environmentProvider = new \PCF\Addendum\Config\SystemEnvironmentProvider();
    $logger = (new \PCF\Addendum\Log\MonologFactory($environmentProvider))->create();
    $httpCacheRuntime = new \PCF\Addendum\Http\Cache\HttpCacheRuntimeFactory(
        new \PCF\Addendum\Http\Cache\HttpCacheConfigurationFactory($environmentProvider),
        new \PCF\Addendum\Http\Cache\HttpCacheBackendProviderFactory()
    )->create();

    return new \PCF\Addendum\Application\App(
        new \PCF\Addendum\Http\Router($routes),
        $logger,
        $httpCacheRuntime
    );
};

PHP;
    }
}
