<?php

/**
 * This file is auto-generated by Addendum. Do not edit it manually.
 */

declare(strict_types=1);


return function (): PCF\Addendum\Http\RouteCollection {
	$routes = new \PCF\Addendum\Http\RouteCollection();

	$routes->addRoute('DELETE', new \PCF\Addendum\Http\RegisteredRoute(pattern: '#^/v1/sessions/current$#', actionClass: \PCF\Addendum\Action\User\DeleteSessionAction::class, middlewares: new \PCF\Addendum\Http\RouteMiddlewareCollection([
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\Auth::class, new \PCF\Addendum\Http\MiddlewareOptions()),
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RequestSignature::class, new \PCF\Addendum\Http\MiddlewareOptions()),
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RateLimitMiddleware::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'rateLimit' => null,
	    ])),
	]), resourcePolicies: new \PCF\Addendum\Http\Cache\ResourcePolicyCollection([
	    new \PCF\Addendum\Attribute\ResourcePolicy(mode: \PCF\Addendum\Http\Cache\HttpCacheMode::PRIVATE, maxAge: 0, resource: '', idAttribute: null, cacheErrors: false),
	]), path: '/v1/sessions/current'));
	$routes->addRoute('DELETE', new \PCF\Addendum\Http\RegisteredRoute(pattern: '#^/v1/users/me$#', actionClass: \PCF\Addendum\Action\User\DeleteUserAction::class, middlewares: new \PCF\Addendum\Http\RouteMiddlewareCollection([
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\Auth::class, new \PCF\Addendum\Http\MiddlewareOptions()),
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RequestSignature::class, new \PCF\Addendum\Http\MiddlewareOptions()),
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RateLimitMiddleware::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'rateLimit' => null,
	    ])),
	]), resourcePolicies: new \PCF\Addendum\Http\Cache\ResourcePolicyCollection([
	    new \PCF\Addendum\Attribute\ResourcePolicy(mode: \PCF\Addendum\Http\Cache\HttpCacheMode::PRIVATE, maxAge: 0, resource: '', idAttribute: null, cacheErrors: false),
	]), path: '/v1/users/me'));
	$routes->addRoute('POST', new \PCF\Addendum\Http\RegisteredRoute(pattern: '#^/v1/users$#', actionClass: \PCF\Addendum\Action\User\PostUserAction::class, middlewares: new \PCF\Addendum\Http\RouteMiddlewareCollection([
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RateLimitMiddleware::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'rateLimit' => new \PCF\Addendum\Attribute\RateLimit(maxAttempts: 5, windowSeconds: 300, scope: 'account', scopeKey: null, errorMessage: null),
	    ])),
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\ValidateRequestAttribute::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'validationRules' => new \PCF\Addendum\Validation\RequestValidationRuleCollection([
	            new \PCF\Addendum\Validation\RequestValidationRule(fieldName: 'email', source: \PCF\Addendum\Validation\RequestFieldSource::Body, constraints: new \PCF\Addendum\Validation\RequestValidationConstraintCollection([
	                new \PCF\Addendum\Validation\Rules\Required(),
	                new \PCF\Addendum\Validation\Rules\Email(),
	                new \PCF\Addendum\Validation\Rules\MaxLength(maxLength: 255),
	            ])),
	            new \PCF\Addendum\Validation\RequestValidationRule(fieldName: 'password', source: \PCF\Addendum\Validation\RequestFieldSource::Body, constraints: new \PCF\Addendum\Validation\RequestValidationConstraintCollection([
	                new \PCF\Addendum\Validation\Rules\Required(),
	                new \PCF\Addendum\Validation\PasswordStrength(),
	            ])),
	        ]),
	    ])),
	]), resourcePolicies: new \PCF\Addendum\Http\Cache\ResourcePolicyCollection([
	    new \PCF\Addendum\Attribute\ResourcePolicy(mode: \PCF\Addendum\Http\Cache\HttpCacheMode::PRIVATE, maxAge: 0, resource: '', idAttribute: null, cacheErrors: false),
	]), path: '/v1/users'));
	$routes->addRoute('POST', new \PCF\Addendum\Http\RegisteredRoute(pattern: '#^/v1/session-refreshes$#', actionClass: \PCF\Addendum\Action\User\PostRefreshSessionAction::class, middlewares: new \PCF\Addendum\Http\RouteMiddlewareCollection([
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RefreshAuth::class, new \PCF\Addendum\Http\MiddlewareOptions()),
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RequestSignature::class, new \PCF\Addendum\Http\MiddlewareOptions()),
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RateLimitMiddleware::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'rateLimit' => null,
	    ])),
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\ValidateRequestAttribute::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'validationRules' => new \PCF\Addendum\Validation\RequestValidationRuleCollection([
	            new \PCF\Addendum\Validation\RequestValidationRule(fieldName: 'jwt_token', source: \PCF\Addendum\Validation\RequestFieldSource::Header, constraints: new \PCF\Addendum\Validation\RequestValidationConstraintCollection([
	                new \PCF\Addendum\Validation\Rules\JwtToken(requiredTokenType: 'user_refresh'),
	            ])),
	        ]),
	    ])),
	]), resourcePolicies: new \PCF\Addendum\Http\Cache\ResourcePolicyCollection([
	    new \PCF\Addendum\Attribute\ResourcePolicy(mode: \PCF\Addendum\Http\Cache\HttpCacheMode::PRIVATE, maxAge: 0, resource: '', idAttribute: null, cacheErrors: false),
	]), path: '/v1/session-refreshes'));
	$routes->addRoute('POST', new \PCF\Addendum\Http\RegisteredRoute(pattern: '#^/v1/sessions$#', actionClass: \PCF\Addendum\Action\User\PostSessionAction::class, middlewares: new \PCF\Addendum\Http\RouteMiddlewareCollection([
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RateLimitMiddleware::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'rateLimit' => new \PCF\Addendum\Attribute\RateLimit(maxAttempts: 5, windowSeconds: 300, scope: 'account', scopeKey: null, errorMessage: null),
	    ])),
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\ValidateRequestAttribute::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'validationRules' => new \PCF\Addendum\Validation\RequestValidationRuleCollection([
	            new \PCF\Addendum\Validation\RequestValidationRule(fieldName: 'email', source: \PCF\Addendum\Validation\RequestFieldSource::Body, constraints: new \PCF\Addendum\Validation\RequestValidationConstraintCollection([
	                new \PCF\Addendum\Validation\Rules\Required(),
	                new \PCF\Addendum\Validation\Rules\Email(),
	            ])),
	            new \PCF\Addendum\Validation\RequestValidationRule(fieldName: 'password', source: \PCF\Addendum\Validation\RequestFieldSource::Body, constraints: new \PCF\Addendum\Validation\RequestValidationConstraintCollection([
	                new \PCF\Addendum\Validation\Rules\Required(),
	            ])),
	        ]),
	    ])),
	]), resourcePolicies: new \PCF\Addendum\Http\Cache\ResourcePolicyCollection([
	    new \PCF\Addendum\Attribute\ResourcePolicy(mode: \PCF\Addendum\Http\Cache\HttpCacheMode::PRIVATE, maxAge: 0, resource: '', idAttribute: null, cacheErrors: false),
	]), path: '/v1/sessions'));
	$routes->addRoute('GET', new \PCF\Addendum\Http\RegisteredRoute(pattern: '#^/v1/users/me$#', actionClass: \PCF\Addendum\Action\User\GetUserAction::class, middlewares: new \PCF\Addendum\Http\RouteMiddlewareCollection([
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\Auth::class, new \PCF\Addendum\Http\MiddlewareOptions()),
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RequestSignature::class, new \PCF\Addendum\Http\MiddlewareOptions()),
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RateLimitMiddleware::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'rateLimit' => null,
	    ])),
	]), resourcePolicies: new \PCF\Addendum\Http\Cache\ResourcePolicyCollection([
	    new \PCF\Addendum\Attribute\ResourcePolicy(mode: \PCF\Addendum\Http\Cache\HttpCacheMode::PRIVATE, maxAge: 0, resource: '', idAttribute: null, cacheErrors: false),
	]), path: '/v1/users/me'));
	$routes->addRoute('GET', new \PCF\Addendum\Http\RegisteredRoute(pattern: '#^/v1/users/(?P<userUuid>[^/]+)$#', actionClass: \PCF\Addendum\Action\User\GetUserAction::class, middlewares: new \PCF\Addendum\Http\RouteMiddlewareCollection([
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\Auth::class, new \PCF\Addendum\Http\MiddlewareOptions()),
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RequestSignature::class, new \PCF\Addendum\Http\MiddlewareOptions()),
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RateLimitMiddleware::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'rateLimit' => null,
	    ])),
	]), resourcePolicies: new \PCF\Addendum\Http\Cache\ResourcePolicyCollection([
	    new \PCF\Addendum\Attribute\ResourcePolicy(mode: \PCF\Addendum\Http\Cache\HttpCacheMode::PRIVATE, maxAge: 0, resource: '', idAttribute: null, cacheErrors: false),
	]), path: '/v1/users/:userUuid'));
	$routes->addRoute('GET', new \PCF\Addendum\Http\RegisteredRoute(pattern: '#^/hello$#', actionClass: \PCF\Addendum\Action\GetHelloAction::class, middlewares: new \PCF\Addendum\Http\RouteMiddlewareCollection([
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RateLimitMiddleware::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'rateLimit' => null,
	    ])),
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\Dummy::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'header' => 'ok',
	    ])),
	]), resourcePolicies: new \PCF\Addendum\Http\Cache\ResourcePolicyCollection([
	    new \PCF\Addendum\Attribute\ResourcePolicy(mode: \PCF\Addendum\Http\Cache\HttpCacheMode::PRIVATE, maxAge: 0, resource: '', idAttribute: null, cacheErrors: false),
	]), path: '/hello'));
	$routes->addRoute('GET', new \PCF\Addendum\Http\RegisteredRoute(pattern: '#^/hello/(?P<name>[^/]+)$#', actionClass: \PCF\Addendum\Action\GetHelloAction::class, middlewares: new \PCF\Addendum\Http\RouteMiddlewareCollection([
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RateLimitMiddleware::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'rateLimit' => null,
	    ])),
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\Dummy::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'header' => 'ok',
	    ])),
	]), resourcePolicies: new \PCF\Addendum\Http\Cache\ResourcePolicyCollection([
	    new \PCF\Addendum\Attribute\ResourcePolicy(mode: \PCF\Addendum\Http\Cache\HttpCacheMode::PRIVATE, maxAge: 0, resource: '', idAttribute: null, cacheErrors: false),
	]), path: '/hello/:name'));
	$routes->addRoute('GET', new \PCF\Addendum\Http\RegisteredRoute(pattern: '#^/dev/auth/token$#', actionClass: \PCF\Addendum\Dev\Action\Auth\GetDevAuthTokenAction::class, middlewares: new \PCF\Addendum\Http\RouteMiddlewareCollection([
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\Auth::class, new \PCF\Addendum\Http\MiddlewareOptions()),
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RequestSignature::class, new \PCF\Addendum\Http\MiddlewareOptions()),
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RateLimitMiddleware::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'rateLimit' => null,
	    ])),
	]), resourcePolicies: new \PCF\Addendum\Http\Cache\ResourcePolicyCollection([
	    new \PCF\Addendum\Attribute\ResourcePolicy(mode: \PCF\Addendum\Http\Cache\HttpCacheMode::PRIVATE, maxAge: 0, resource: '', idAttribute: null, cacheErrors: false),
	]), path: '/dev/auth/token'));
	$routes->addRoute('GET', new \PCF\Addendum\Http\RegisteredRoute(pattern: '#^/dev/http-cache/articles/(?P<articleUuid>[^/]+)$#', actionClass: \PCF\Addendum\Dev\Action\HttpCache\GetDevHttpCacheArticleAction::class, middlewares: new \PCF\Addendum\Http\RouteMiddlewareCollection([
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RateLimitMiddleware::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'rateLimit' => null,
	    ])),
	]), resourcePolicies: new \PCF\Addendum\Http\Cache\ResourcePolicyCollection([
	    new \PCF\Addendum\Attribute\ResourcePolicy(mode: \PCF\Addendum\Http\Cache\HttpCacheMode::PUBLIC, maxAge: 60, resource: 'article', idAttribute: 'articleUuid', cacheErrors: false),
	]), path: '/dev/http-cache/articles/:articleUuid'));
	$routes->addRoute('HEAD', new \PCF\Addendum\Http\RegisteredRoute(pattern: '#^/dev/http-cache/articles/(?P<articleUuid>[^/]+)$#', actionClass: \PCF\Addendum\Dev\Action\HttpCache\GetDevHttpCacheArticleAction::class, middlewares: new \PCF\Addendum\Http\RouteMiddlewareCollection([
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RateLimitMiddleware::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'rateLimit' => null,
	    ])),
	]), resourcePolicies: new \PCF\Addendum\Http\Cache\ResourcePolicyCollection([
	    new \PCF\Addendum\Attribute\ResourcePolicy(mode: \PCF\Addendum\Http\Cache\HttpCacheMode::PUBLIC, maxAge: 60, resource: 'article', idAttribute: 'articleUuid', cacheErrors: false),
	]), path: '/dev/http-cache/articles/:articleUuid'));
	$routes->addRoute('OPTIONS', new \PCF\Addendum\Http\RegisteredRoute(pattern: '#^/dev/http-cache/articles/(?P<articleUuid>[^/]+)$#', actionClass: \PCF\Addendum\Dev\Action\HttpCache\GetDevHttpCacheArticleAction::class, middlewares: new \PCF\Addendum\Http\RouteMiddlewareCollection([
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RateLimitMiddleware::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'rateLimit' => null,
	    ])),
	]), resourcePolicies: new \PCF\Addendum\Http\Cache\ResourcePolicyCollection([
	    new \PCF\Addendum\Attribute\ResourcePolicy(mode: \PCF\Addendum\Http\Cache\HttpCacheMode::PUBLIC, maxAge: 60, resource: 'article', idAttribute: 'articleUuid', cacheErrors: false),
	]), path: '/dev/http-cache/articles/:articleUuid'));
	$routes->addRoute('PATCH', new \PCF\Addendum\Http\RegisteredRoute(pattern: '#^/dev/http-cache/articles/(?P<articleUuid>[^/]+)$#', actionClass: \PCF\Addendum\Dev\Action\HttpCache\PatchDevHttpCacheArticleAction::class, middlewares: new \PCF\Addendum\Http\RouteMiddlewareCollection([
	    new \PCF\Addendum\Http\RouteMiddleware(\PCF\Addendum\Http\Middleware\RateLimitMiddleware::class, new \PCF\Addendum\Http\MiddlewareOptions(additionalData: [
	        'rateLimit' => null,
	    ])),
	]), resourcePolicies: new \PCF\Addendum\Http\Cache\ResourcePolicyCollection([
	    new \PCF\Addendum\Attribute\ResourcePolicy(mode: \PCF\Addendum\Http\Cache\HttpCacheMode::PUBLIC, maxAge: 60, resource: 'article', idAttribute: 'articleUuid', cacheErrors: false),
	]), path: '/dev/http-cache/articles/:articleUuid'));

	return $routes;
};
